movieproject/movieapp/urls.py
from django.urls import path

from movieapp import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
     path('delete/<int:movie_id>/',views.delete,name='delete'),
    path('update/<int:movie_id>/', views.update, name='update')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    des=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pictures')


    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from  .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model= Movie
        fields=['name','des','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list': movie
    }

    return render(request,'index.html',context)
def details(request,movie_id):
    obj=Movie.objects.get(id=movie_id)
    return render(request,"details.html", {'movie':obj})

def add_movie(request):
    if request.method=='POST':
        name= request.POST.get('name',)
        des = request.POST.get('des',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,des=des,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form': form, 'movie': movie})

def delete(request, movie_id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=movie_id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text", name='name', placeholder="Movie name">
    <input type="text", name='des', placeholder="description">
    <input type="text", name='year', placeholder="year">
    <input type="file", name='img'>
    <input type="submit">
</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      MOVIES
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    ARE YOU SURE TO DELETE THIS MOVIE?
    <input type="submit">
</form>

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="500" height="500"><br>
        </div>
<div class="col-md-6">
    <h5>{{movie.name}}</h5>
   <h6> {{movie.des}}</h6>
    <h5>{{movie.year}}</h5>

     <a class="btn btn-warning" href="{% url 'movieapp:update' movie_id=movie.id %}">Update</a>
     <a class="btn btn-danger" href="{% url 'movieapp:delete' movie_id=movie.id %}">Delete</a>
</div>

    </div>
</div>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem; margin-bottom: 20px;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="150px" height="250px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.des}}</p>
                    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">VIEW MORE</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

movieproject/templates/update.html
{% extends 'base.html' %}
{% block body %}


<form method='POST' enctype="multipart/form-data">
    {%csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>
{% endblock %}